---

- name: Install Utils
  hosts: localhost
  remote_user: root

  tasks:
    - name: Download Hack Font
      when: ansible_facts['os_family'] == "Darwin"
      get_url:
        url: https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip
        dest: /tmp/hack_font.zip

    - name: Install Hack Font
      when: ansible_facts['os_family'] == "Darwin"
      unarchive:
        src: /tmp/hack_font.zip
        dest: /Library/Fonts
